#!/bin/bash
IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "MASTER_IP=$IP"
sed -i s/MASTER/$IP/ /etc/hadoop/core-site.xml
sudo -u hdfs hadoop namenode -format
service hadoop-namenode start
/opt/configure_shark.sh $IP
sleep 5
nohup sudo -u hdfs /opt/run_shark_master.sh $IP &
sleep 20
cd /opt/metastore && sudo -u hdfs /opt/shark-0.7.0/bin/shark
